##### VARIABLES
@SERVER = http://localhost:8080/api/todos
@USER_ID = XXXXXXXXXXXXXXXX
@TODO_ID = XXXXXXXXXXXXXXXX
@USER = user
@PASSWORD = 123456
@TOKEN = eyJhbGciOiJIUzM4NCJ9.eyJzdWIiOiJuZW9AZ21haWwuY29tIiwiaXNzIjoiRFlMVVQyMDAwIiwiaWF0IjoxNzUzMjc1MDQ5LCJleHAiOjE3NTMyNzg2NDl9._ebRJwcmw8NZX9ThLTzsyL89FrRL0bjbQwt9pviG5Y1OUofUmq-xDAr74wUFFdXI


##### GET ALL TODOS
GET {{SERVER}}
Content-Type: application/json
Authorization: Bearer {{TOKEN}}



##### GET ALL TODOS BY USER_ID
GET {{SERVER}}/{{USER_ID}}



##### DELETE BY TODO_ID
DELETE {{SERVER}}/{{TODO_ID}}



##### UPDATE TODO
PUT {{SERVER}}/{{TODO_ID}}
Content-Type: application/json

{
  "done": true,
  "title": "Hi there!!!"
}




























