##### VARIABLES
@SERVER = http://localhost:8080/api/users
@USER = user
@PASSWORD = 123456
@TOKEN = eyJhbGciOiJIUzM4NCJ9.eyJzdWIiOiJuZW9AZ21haWwuY29tIiwiaXNzIjoiRFlMVVQyMDAwIiwiaWF0IjoxNzUzMjcwMjk0LCJleHAiOjE3NTMyNzM4OTR9.CiJrsktLippHVzDgMaDo26D-q2LnCgcHtUnuWi7g9NHzXlbkoOmP7LsB3Xp0oEZ9



##### REGISTER USER
POST {{SERVER}}/register
Content-Type: application/json

{
  "username": "neo@gmail.com",
  "password": "123456",
  "role": "USER"
}



##### LOGIN USER
POST {{SERVER}}/login
Content-Type: application/json

{
  "username": "neo@gmail.com",
  "password": "123456"
}






















